server:
  port: {{server.port}}

spring:
   profiles:
      active: {{spring.profiles.active}}
   datasource:
     driverClassName: {{spring.datasource.driverClassName}}
     url: {{spring.datasource.url}}
     username: {{spring.datasource.username}}
     password: {{spring.datasource.password}}
   jpa:
      database-platform: {{spring.jpa.database-platform}}
      show-sql: {{spring.jpa.show-sql}}
      hibernate.ddl-auto: {{spring.jpa.update}}
   servlet:
      multipart:
         enabled: {{spring.servlet.multipart.enabled}}

logging:
  level:
    org:
       springframework: {{logging.level.org.springframework}}